name: New PR created
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
  e2e-linux:
    uses: ./.github/workflows/e2e-linux.yml